{"cells": [{"metadata": {"trusted": true}, "cell_type": "code", "source": "import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib as mpl\nimport seaborn as sns\nimport datadotworld as ddw\nimport re\nimport json\n%matplotlib inline\nfrom log_progress import log_progress # https://github.com/alexanderkuk/log-progress\n\n%config InlineBackend.figure_format = 'retina'\n\npd.set_option('display.max_rows', 40)\npd.set_option('display.max_columns', 500)\npd.set_option('display.width', 1000)\n#pd.set_option('max_colwidth', 70)", "execution_count": 1, "outputs": []}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "dataset = 'uscensusbureau/acs-2015-5-e-housing'\n\ndata = ddw.load_dataset(dataset)", "execution_count": 2, "outputs": []}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "states = pd.Series([i for i in data.tables.keys()])\nstates.drop(states[states.str.len() != 2].index, inplace=True)\nstates.reset_index(drop=True, inplace=True)", "execution_count": 3, "outputs": []}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "cols = ['statefips', 'countyfips', 'b25010_001', 'areaname']", "execution_count": 4, "outputs": []}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "count = 0\nfor i in states.values:\n    if count == 0:\n        df = data.dataframes[i].loc[data.dataframes[i].summarylevel==50, cols]\n    else:\n        df = pd.concat([df, data.dataframes[i].loc[data.dataframes[i].summarylevel==50, cols]], axis=0)\n    count += 1\ndf.reset_index(drop=True, inplace=True)    ", "execution_count": 5, "outputs": [{"output_type": "stream", "text": "/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ak schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using al schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ar schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using az schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ca schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using co schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ct schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using dc schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using de schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using fl schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ga schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using hi schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ia schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using id schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using il schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using in schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ks schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ky schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using la schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ma schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using md schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using me schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using mi schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using mn schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using mo schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ms schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n", "name": "stderr"}, {"output_type": "stream", "text": "/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using mt schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using nc schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using nd schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ne schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using nh schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using nj schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using nm schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using nv schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ny schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using oh schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ok schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using or schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using pa schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using pr schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ri schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using sc schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using sd schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using tn schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using tx schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using ut schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using va schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using vt schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using wa schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using wi schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using wv schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n/Users/noahrippner/anaconda/envs/anaconda-py3/lib/python3.6/site-packages/datadotworld/models/dataset.py:192: UserWarning: Unable to set data frame dtypes automatically using wy schema. Data types may need to be adjusted manually. Error: Integer column has NA values in column 3\n  'Error: {}'.format(resource_name, e))\n", "name": "stderr"}]}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "df['statefips'] = df.statefips.astype('str')\ndf['countyfips'] = df.countyfips.astype('int')\ndf['countyfips'] = df.countyfips.astype('str')\ndf['countyfips'] = df.countyfips.str.pad(3, fillchar='0')", "execution_count": 6, "outputs": []}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "df.rename(columns={'b25010_001':'avghouseholdsize', 'areaname':'geography'}, inplace=True)", "execution_count": 7, "outputs": []}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "with ddw.open_remote_file('exercises/linear-regression-exercise-1', 'avg-household-size.csv') as f:\n    df.to_csv(f, index=False)", "execution_count": 8, "outputs": []}, {"metadata": {"trusted": true}, "cell_type": "code", "source": "", "execution_count": null, "outputs": []}], "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"}, "language_info": {"name": "python", "version": "3.6.4", "mimetype": "text/x-python", "codemirror_mode": {"name": "ipython", "version": 3}, "pygments_lexer": "ipython3", "nbconvert_exporter": "python", "file_extension": ".py"}, "toc": {"threshold": 4, "number_sections": true, "toc_cell": false, "toc_window_display": false, "toc_section_display": "block", "sideBar": true, "navigate_menu": true, "moveMenuLeft": true, "widenNotebook": false, "colors": {"hover_highlight": "#DAA520", "selected_highlight": "#FFD700", "running_highlight": "#FF0000", "wrapper_background": "#FFFFFF", "sidebar_border": "#EEEEEE", "navigate_text": "#333333", "navigate_num": "#000000"}, "nav_menu": {"height": "12px", "width": "252px"}}, "varInspector": {"window_display": false, "cols": {"lenName": 16, "lenType": 16, "lenVar": 40}, "kernels_config": {"python": {"library": "var_list.py", "delete_cmd_prefix": "del ", "delete_cmd_postfix": "", "varRefreshCmd": "print(var_dic_list())"}, "r": {"library": "var_list.r", "delete_cmd_prefix": "rm(", "delete_cmd_postfix": ") ", "varRefreshCmd": "cat(var_dic_list()) "}}, "types_to_exclude": ["module", "function", "builtin_function_or_method", "instance", "_Feature"]}}, "nbformat": 4, "nbformat_minor": 2}